export interface ArrivalAssistedProduct {
    sCodProduct:string
    sLotNumber:string
    sProductDescription:string
    sUnit:string
    sPurchaseUnit:string
    nUnitsXbox:number
    sExpDate:string
    sProduct_Owner:string
    sZona:string
    sCat01:string
    boxesOnPalet:number
    sPalletId:string
    sPalletLocation:string
    default_location:string
    suggested_target_location:string
    used_on_production:string
    used_on_relocation:string
}
